[build]
  publish = "."
  command = "echo Static VIAM CMS"

[functions]
  directory = "netlify/functions"

[functions.transcribe-audio]
  timeout = 26

[functions.transcribe-proxy]
  timeout = 300

[[redirects]]
  from = "/video_diamante"
  to = "/video_diamante.html"
  status = 200

[[redirects]]
  from = "/musica"
  to = "/musica.html"
  status = 200
