window.CURSO_SLIDES = [
  {
    etapa: "Portada",
    kicker: "CMS VIAM · Escuela de principios",
    title: "La palabra que no obliga",
    text: "Convencer sin quitarle a nadie la voluntad. Primero se oye. Luego se deposita confianza. Después se habla.",
    note: "Curso gradual para el consultorio. Ciencia seria, lenguaje claro, práctica cotidiana.",
    image: "/cursos-assets/la-palabra-que-no-obliga/01-portada-palabra-no-obliga.jpg",
    alt: "Dos personas a la mesa: una escucha de verdad",
  },
  {
    etapa: "Umbral",
    kicker: "Regla que no se negocia",
    title: "Al lado del profesional, nunca en su lugar",
    text: "Si hay control, chantaje, violencia o una venta que se aprovecha del miedo, la primera parada es clínica y de protección.",
    note: "Este curso no enseña a manipular. Enseña a reconocer el gancho y a hablar sin tomar la voluntad.",
    image: "/cursos-assets/la-palabra-que-no-obliga/09-lampara-mesa.jpg",
    alt: "Lámpara en la mesa, no incendio",
  },
  {
    etapa: "Umbral",
    kicker: "Cómo vamos a aprender",
    title: "De menor a mayor",
    text: "Primero el principio. Luego la imagen. Luego la vida cotidiana. Al final, un puente bíblico que convenza a la mente.",
    note: "Ocho etapas. Un ejercicio por sesión. Crecimiento rápido, no forzado.",
    image: "/cursos-assets/la-palabra-que-no-obliga/10-caminar-junto.jpg",
    alt: "Caminar junto, no empujar",
  },
  {
    etapa: "1",
    kicker: "Etapa 1 · Oír antes de mover",
    title: "El otro pregunta si lo viste o lo usaste",
    text: "La mente no es un tribunal. Es un clima. Primero siente si hay suelo. Después inventa razones.",
    note: "Quien habla primero, a menudo llega tarde.",
    image: "/cursos-assets/la-palabra-que-no-obliga/02-escuchar-antes.jpg",
    alt: "El taller espera; el oído, no",
  },
  {
    etapa: "1",
    kicker: "Etapa 1",
    title: "No es meter una idea",
    text: "Es acompañar a que la persona mire lo que ya estaba ahí. Si tu frase necesita que el otro se encoga, es palanca, no palabra.",
    note: "La palanca mueve un cuerpo. No mueve una voluntad libre.",
    image: "/cursos-assets/la-palabra-que-no-obliga/01-portada-palabra-no-obliga.jpg",
    alt: "La mesa de la conversación",
  },
  {
    etapa: "1",
    kicker: "Cuento",
    title: "La olla que no se vendía",
    text: "El sobrino recitaba ventajas. Doña Remedios preguntó para cuántos cocina los domingos. Ganó el domingo vacío, no el catálogo.",
    note: "Las herramientas pueden esperar. El oído, no.",
    image: "/cursos-assets/la-palabra-que-no-obliga/02-escuchar-antes.jpg",
    alt: "Oír el oficio del otro",
  },
  {
    etapa: "1",
    kicker: "Puente bíblico",
    title: "Responder antes de oír",
    text: "Proverbios 18:13: locura y oprobio. Jehová no pide mudez. Pide que el oído llegue primero.",
    note: "La sentencia lista cubre el apuro propio. No sirve al otro.",
    image: "/cursos-assets/la-palabra-que-no-obliga/05-voz-silencio.jpg",
    alt: "Espacio para oír",
  },
  {
    etapa: "1",
    kicker: "Ejercicio",
    title: "Una pregunta y ninguna tesis",
    text: "Prohíbete el consejo hasta una pregunta verdadera y el silencio de oír. Anota si oías para responder.",
    note: "¿Entré a convencer, o entré a ver?",
    image: "/cursos-assets/la-palabra-que-no-obliga/02-escuchar-antes.jpg",
    alt: "Callar las herramientas",
  },
  {
    etapa: "2",
    kicker: "Etapa 2 · El suelo de la confianza",
    title: "La idea se cae si el piso está hueco",
    text: "La confianza no se declara. Se vierte, se nivela y se deja secar. Cada «ahorita vengo» que no vuelve es una grieta.",
    note: "Nadie pone el segundo piso sobre un nivel que miente.",
    image: "/cursos-assets/la-palabra-que-no-obliga/03-suelo-confianza.jpg",
    alt: "La burbuja en el centro",
  },
  {
    etapa: "2",
    kicker: "Etapa 2",
    title: "La cara, la voz y el hecho",
    text: "El cuerpo detecta la incongruencia más rápido que el argumento. Impresionar es ruido. Hacer sentir suelo es oficio.",
    note: "Agradar a todos es perder el peso.",
    image: "/cursos-assets/la-palabra-que-no-obliga/03-suelo-confianza.jpg",
    alt: "Cimiento al amanecer",
  },
  {
    etapa: "2",
    kicker: "Cuento",
    title: "El nivel que no mentía",
    text: "Uno prometió sábado y llegó lunes. El otro midió y avisó jueves. A los seis meses se sabía a quién llamar cuando el muro no podía mentir.",
    note: "No ganó el discurso. Ganó el nivel.",
    image: "/cursos-assets/la-palabra-que-no-obliga/03-suelo-confianza.jpg",
    alt: "El oficio del nivel",
  },
  {
    etapa: "2",
    kicker: "Puente bíblico",
    title: "El buen nombre",
    text: "Proverbios 22:1: de más estima que las muchas riquezas. Jehová mide si el nombre todavía se puede pisar.",
    note: "La riqueza de la palabra es que alguien pueda apoyarse sin caerse.",
    image: "/cursos-assets/la-palabra-que-no-obliga/10-caminar-junto.jpg",
    alt: "Suelo compartido",
  },
  {
    etapa: "2",
    kicker: "Ejercicio",
    title: "Una grieta y un centímetro",
    text: "Cierra hoy una promesa a medias, o di con claridad que no podrás. Un solo centímetro. No toda la casa.",
    note: "¿Pides que te crean sobre un piso que no nivelaste?",
    image: "/cursos-assets/la-palabra-que-no-obliga/03-suelo-confianza.jpg",
    alt: "Un centímetro de suelo",
  },
  {
    etapa: "3",
    kicker: "Etapa 3 · El clima de la mesa",
    title: "El pulso decide antes que el argumento",
    text: "El miedo estrecha. La ira acelera. Luego llega la lógica a justificar lo que el pecho ya firmó.",
    note: "Quien no gobierna su clima entrega el volante al que grite más cerca.",
    image: "/cursos-assets/la-palabra-que-no-obliga/04-clima-mesa.jpg",
    alt: "Dos climas, una cocina",
  },
  {
    etapa: "3",
    kicker: "Etapa 3",
    title: "El miedo vende barato",
    text: "Obedecer por susto es rápido. Quedarse de buena gana es otra cosa. Aquí no se enseña a asustar. Se enseña a no firmar ahí.",
    note: "Autocontrol no es apagar el corazón. Es no entregarle la pluma.",
    image: "/cursos-assets/la-palabra-que-no-obliga/04-clima-mesa.jpg",
    alt: "La taza en calma",
  },
  {
    etapa: "3",
    kicker: "Cuento",
    title: "El tío y la tía",
    text: "El tío golpeaba la mesa. Carmen sirvió agua y preguntó qué apretaba. El argumento llegó cuando ya había mesa.",
    note: "La carne no cambió de sabor. Cambió el clima.",
    image: "/cursos-assets/la-palabra-que-no-obliga/04-clima-mesa.jpg",
    alt: "Bajar el volumen de la sala",
  },
  {
    etapa: "3",
    kicker: "Puente bíblico",
    title: "Tardarse en airarse",
    text: "Proverbios 16:32: mejor que el fuerte; enseñorearse del espíritu, mejor que tomar una ciudad.",
    note: "Jehová no pide un santo de yeso. Pide rienda. Tomar la ciudad y perderte es mal negocio.",
    image: "/cursos-assets/la-palabra-que-no-obliga/05-voz-silencio.jpg",
    alt: "Rienda antes de la boca",
  },
  {
    etapa: "3",
    kicker: "Ejercicio",
    title: "Nombrar el clima",
    text: "Antes: «ahora mismo siento ______». Después: ¿firmé con el pulso alto? No corrijas al otro. Mide tu clima.",
    note: "¿Quién pone el clima de tus sí: tú, o el susto más cercano?",
    image: "/cursos-assets/la-palabra-que-no-obliga/08-cuaderno-amanecer.jpg",
    alt: "Una línea antes de hablar",
  },
  {
    etapa: "4",
    kicker: "Etapa 4 · La voz y el silencio",
    title: "Las palabras son la parte chica",
    text: "El cerebro oye la música antes que la letra. Llenar el silencio suele ser miedo a no gustar.",
    note: "El silencio bien usado es espacio para que el otro se oiga.",
    image: "/cursos-assets/la-palabra-que-no-obliga/05-voz-silencio.jpg",
    alt: "La silla del silencio",
  },
  {
    etapa: "4",
    kicker: "Etapa 4",
    title: "Nombrar sin diagnosticar",
    text: "«Parece que esto te pesó.» No es técnica de venta. Es un espejo que el otro puede corregir.",
    note: "Cuando alguien se siente luchado, se cierra. Cuando se siente oído, puede mirar.",
    image: "/cursos-assets/la-palabra-que-no-obliga/01-portada-palabra-no-obliga.jpg",
    alt: "Devolver el clima",
  },
  {
    etapa: "4",
    kicker: "Cuento",
    title: "El locutor y la maestra",
    text: "Él no dejaba hueco. Ella dijo una frase y esperó. En ese hueco un padre pudo ser torpe sin humillación.",
    note: "No ganó el volumen. Ganó el permiso.",
    image: "/cursos-assets/la-palabra-que-no-obliga/05-voz-silencio.jpg",
    alt: "Un hueco que sostiene",
  },
  {
    etapa: "4",
    kicker: "Puente bíblico",
    title: "Manzana de oro",
    text: "Proverbios 25:11: la palabra dicha como conviene. Colosenses 4:6: con gracia, sazonada con sal.",
    note: "Jehová no pide un discurso largo. Pide sazón: ni soso ni que queme.",
    image: "/cursos-assets/la-palabra-que-no-obliga/09-lampara-mesa.jpg",
    alt: "La palabra a su hora",
  },
  {
    etapa: "4",
    kicker: "Ejercicio",
    title: "Tres respiraciones y un nombre",
    text: "Silencio cuando el otro termina. Luego el clima, no tu tesis. Si se defiende, quizá el tono todavía empujaba.",
    note: "¿Llenas el silencio porque sirves, o porque no aguantas no ser oído?",
    image: "/cursos-assets/la-palabra-que-no-obliga/05-voz-silencio.jpg",
    alt: "Sostener el hueco",
  },
  {
    etapa: "5",
    kicker: "Etapa 5 · Quien dirige tu mirada",
    title: "La atención se alquila",
    text: "Si muchos miran, parece valioso. Si se acaba, urgente. Si una cara conocida lo dice, cierto. Atajos para cruzar. También para firmar.",
    note: "Quien no pregunta de quién es el anuncio compra una vida prestada.",
    image: "/cursos-assets/la-palabra-que-no-obliga/06-vitrina-atencion.jpg",
    alt: "El escaparate pide la mirada",
  },
  {
    etapa: "5",
    kicker: "Etapa 5",
    title: "Tres preguntas lentas",
    text: "¿Quién gana si creo esto? ¿Qué emoción me sirven? ¿Lo quiero cuando baja el ruido?",
    note: "No toda influencia es delito. El problema es la que no se declara.",
    image: "/cursos-assets/la-palabra-que-no-obliga/06-vitrina-atencion.jpg",
    alt: "Detenerse antes de entrar",
  },
  {
    etapa: "5",
    kicker: "Cuento",
    title: "La fila de tres",
    text: "Tres conocidos «hacían fila». Ella vio el saludo cómplice y se preguntó si lo quería. Se fue con el criterio intacto.",
    note: "No era desprecio al comercio. Era no alquilar la mirada.",
    image: "/cursos-assets/la-palabra-que-no-obliga/06-vitrina-atencion.jpg",
    alt: "Devolver el anuncio",
  },
  {
    etapa: "5",
    kicker: "Puente bíblico",
    title: "Probad los espíritus",
    text: "1 Juan 4:1: no creáis a todo espíritu. Proverbios 13:20: la compañía también persuade.",
    note: "Jehová no pide cinismo. Pide examen. Elige con quién te dejas mirar el mundo.",
    image: "/cursos-assets/la-palabra-que-no-obliga/08-cuaderno-amanecer.jpg",
    alt: "Examinar lo que entra",
  },
  {
    etapa: "5",
    kicker: "Ejercicio",
    title: "Devolver el anuncio",
    text: "Un sí con prisa. Tres renglones: quién empujó, qué emoción, qué dirías si nadie te viera.",
    note: "No deshagas toda la semana. Recupera un sí.",
    image: "/cursos-assets/la-palabra-que-no-obliga/06-vitrina-atencion.jpg",
    alt: "La vitrina y la pregunta",
  },
  {
    etapa: "6",
    kicker: "Etapa 6 · La presencia quieta",
    title: "No se actúa. Se sostiene.",
    text: "Quien entra explicando su valor empuja el cuarto hacia atrás. Quien pregunta algo útil deja que el cuarto se organice.",
    note: "Si tu valor depende del aplauso de esta hora, ya entregaste el peso de estar.",
    image: "/cursos-assets/la-palabra-que-no-obliga/07-presencia-quieta.jpg",
    alt: "Llegar entero, sin teatro",
  },
  {
    etapa: "6",
    kicker: "Etapa 6",
    title: "El silencio como mueble",
    text: "Para quien mendiga, el silencio es precipicio. Para quien se sostiene, se puede sentar. La arrogancia es la misma hambre con otra máscara.",
    note: "No se improvisa el domingo. Se practica en los lunes sin público.",
    image: "/cursos-assets/la-palabra-que-no-obliga/07-presencia-quieta.jpg",
    alt: "El umbral sin ruido",
  },
  {
    etapa: "6",
    kicker: "Cuento",
    title: "El ingeniero y la pregunta",
    text: "Uno trajo diez minutos de currículum. El otro preguntó cuándo bajó el nivel del pozo. El dueño supo a quién llamar.",
    note: "La presencia no fue el maletín. Fue no necesitarlo para merecer la silla.",
    image: "/cursos-assets/la-palabra-que-no-obliga/07-presencia-quieta.jpg",
    alt: "Una silla merecida",
  },
  {
    etapa: "6",
    kicker: "Puente bíblico",
    title: "El sabio en reposo",
    text: "Eclesiastés 9:17: las palabras del sabio en reposo son oídas más que el clamor.",
    note: "Jehová no mide el decibel. Mide si hay reposo detrás de la boca.",
    image: "/cursos-assets/la-palabra-que-no-obliga/05-voz-silencio.jpg",
    alt: "Reposo, no clamor",
  },
  {
    etapa: "6",
    kicker: "Ejercicio",
    title: "Entrar sin venderte",
    text: "Diez minutos sin un logro propio. Saluda. Pregunta. Sostén un silencio. Anota qué hambre apareció.",
    note: "Esa hambre es material de trabajo, no de vergüenza.",
    image: "/cursos-assets/la-palabra-que-no-obliga/07-presencia-quieta.jpg",
    alt: "No vender el umbral",
  },
  {
    etapa: "7",
    kicker: "Etapa 7 · El diálogo que te habita",
    title: "El orador de las cinco de la mañana",
    text: "«No alcanzo.» «Si no me aprueban, no valgo.» Esa voz persuade más que cualquier vendedor: tiene acceso las veinticuatro horas.",
    note: "Antes de convencer a nadie, ya te estás convenciendo a ti.",
    image: "/cursos-assets/la-palabra-que-no-obliga/08-cuaderno-amanecer.jpg",
    alt: "El primer auditorio",
  },
  {
    etapa: "7",
    kicker: "Etapa 7",
    title: "La mente cree lo que se repite con clima",
    text: "No es pensamiento mágico. Es higiene: dejar de sembrar cada mañana una sentencia que te achica.",
    note: "Si no eliges la dieta, alguien elige por ti.",
    image: "/cursos-assets/la-palabra-que-no-obliga/08-cuaderno-amanecer.jpg",
    alt: "Una línea verdadera",
  },
  {
    etapa: "7",
    kicker: "Cuento",
    title: "La frase del taller",
    text: "«Yo no sirvo para números» hasta que el aprendiz dejó de traer las cuentas. Ella escribió: «puedo revisar una columna».",
    note: "El taller no cambió de techo. Cambió de oración.",
    image: "/cursos-assets/la-palabra-que-no-obliga/08-cuaderno-amanecer.jpg",
    alt: "El hecho pequeño",
  },
  {
    etapa: "7",
    kicker: "Puente bíblico",
    title: "Como piensa en su corazón",
    text: "Proverbios 23:7. Filipenses 4:8 es dieta: lo verdadero, lo honesto, lo justo.",
    note: "Jehová no pide que niegues el dolor. Pide que no sea tu único alimento.",
    image: "/cursos-assets/la-palabra-que-no-obliga/09-lampara-mesa.jpg",
    alt: "Guardar lo que entra",
  },
  {
    etapa: "7",
    kicker: "Ejercicio",
    title: "Una línea que no sea un juicio",
    text: "La frase que te achica. Al lado, una línea pequeña sostenida con un hecho de hoy. Al anochecer, ¿siguió firmando la vieja?",
    note: "No «soy un genio». «Puedo revisar una columna.»",
    image: "/cursos-assets/la-palabra-que-no-obliga/08-cuaderno-amanecer.jpg",
    alt: "Hecho al alba",
  },
  {
    etapa: "8",
    kicker: "Etapa 8 · Lámpara, no incendio",
    title: "El mismo fuego ilumina o quema",
    text: "Saber cómo se mueve una mente no te da derecho a tomarla. Te da oficio, y te da juicio.",
    note: "El manipulador vende el remedio a la inseguridad que él encendió. El oficio digno devuelve el volante.",
    image: "/cursos-assets/la-palabra-que-no-obliga/09-lampara-mesa.jpg",
    alt: "Lámpara que sirve",
  },
  {
    etapa: "8",
    kicker: "Etapa 8",
    title: "Dejar de ser el que dice que sí por hambre",
    text: "Si mueves a otros y sigues esclavo de tu aplauso, solo cambiaste de teatro. La batalla seria es adentro.",
    note: "Caminar junto no es empujar. Es la misma vereda, sin correa.",
    image: "/cursos-assets/la-palabra-que-no-obliga/10-caminar-junto.jpg",
    alt: "El mismo paso",
  },
  {
    etapa: "8",
    kicker: "Cuento",
    title: "Dos puestos, un mismo producto",
    text: "Uno gritaba «se acaba». El otro dejaba probar y no apuraba. Al mes el barrio sabía a quién creerle el maíz.",
    note: "El producto era el mismo. El fuego, no.",
    image: "/cursos-assets/la-palabra-que-no-obliga/10-caminar-junto.jpg",
    alt: "Oficio que se puede volver a visitar",
  },
  {
    etapa: "8",
    kicker: "Puente bíblico",
    title: "La lengua y la lámpara",
    text: "Santiago 3: la lengua incendia. Mateo 5:15-16: la lámpara alumbra a los de casa. Que vean la obra, no el humo.",
    note: "Jehová no pide que apagues la palabra. Pide candelero, no rastrojo.",
    image: "/cursos-assets/la-palabra-que-no-obliga/09-lampara-mesa.jpg",
    alt: "Candelero, no incendio",
  },
  {
    etapa: "8",
    kicker: "Ejercicio",
    title: "Lámpara o palanca",
    text: "Antes: ¿servir o cobrar? Después: oí; no firmé en susto; no usé culpa; dejé el sí en sus manos.",
    note: "Si falló una, mañana otra vez. El cuaderno no es galería.",
    image: "/cursos-assets/la-palabra-que-no-obliga/10-caminar-junto.jpg",
    alt: "Dejar el sí en sus manos",
  },
  {
    etapa: "Cierre",
    kicker: "Pregunta que te acompaña",
    title: "¿A quién alumbrarías, a quién dejarías de empujar?",
    text: "Si tu palabra de mañana fuera lámpara y no incendio, ¿a quién serviría primero?",
    note: "El gancho puede volver. El oído ya tiene asiento. Al lado del profesional, nunca en su lugar.",
    image: "/cursos-assets/la-palabra-que-no-obliga/01-portada-palabra-no-obliga.jpg",
    alt: "La mesa, otra vez, con elección",
  },
]
