window.CURSO_SLIDES = [
  {
    etapa: "Portada",
    kicker: "CMS VIAM · Escuela de principios",
    title: "La pausa que decide",
    text: "Dejar de vivir reaccionando. Observar, decidir sin la tormenta y diseñar el día con serenidad.",
    note: "Curso gradual para el consultorio. Ciencia seria, lenguaje claro, práctica cotidiana.",
    image: "/cursos-assets/la-pausa-que-decide/01-portada-pausa-decide.jpg",
    alt: "Una persona se detiene en un cruce al atardecer",
  },
  {
    etapa: "Umbral",
    kicker: "Regla que no se negocia",
    title: "Al lado del profesional, nunca en su lugar",
    text: "Si la impulsividad ya daña —juego, deudas, crisis, ánimo que se dispara o se apaga— la primera parada es clínica.",
    note: "Este curso no sustituye psicoterapia ni tratamiento. Añade una pregunta mientras se cumple el plan.",
    image: "/cursos-assets/la-pausa-que-decide/08-mente-filtro.jpg",
    alt: "Mesa en calma, el teléfono boca abajo",
  },
  {
    etapa: "Umbral",
    kicker: "Cómo vamos a aprender",
    title: "De menor a mayor",
    text: "Primero el principio. Luego la imagen. Luego la vida cotidiana. Al final, un puente bíblico que convenza a la mente.",
    note: "Ocho etapas. Un ejercicio por sesión. Crecimiento rápido, no forzado.",
    image: "/cursos-assets/la-pausa-que-decide/03-bosque-dos-miradas.jpg",
    alt: "Dos caminantes, dos formas de mirar",
  },
  {
    etapa: "1",
    kicker: "Etapa 1 · Dejar de reaccionar",
    title: "El estímulo quiere firmar por ti",
    text: "El día está diseñado para que contestes en caliente. Quien no pone pausa habita una biografía que no eligió.",
    note: "Pensar con estrategia no es manipular. Es recuperar el volante.",
    image: "/cursos-assets/la-pausa-que-decide/02-reaccion-pausa.jpg",
    alt: "Uno corre; el otro se detiene",
  },
  {
    etapa: "1",
    kicker: "Etapa 1",
    title: "Cientos de sí pequeños",
    text: "La vida no se decide en un golpe de suerte. Se arma con respuestas mínimas: un mensaje, una compra, un compromiso.",
    note: "La pausa no es pereza. Es el único lugar donde todavía puedes elegir.",
    image: "/cursos-assets/la-pausa-que-decide/01-portada-pausa-decide.jpg",
    alt: "El cruce espera",
  },
  {
    etapa: "1",
    kicker: "Cuento",
    title: "El vecino que contestaba todo",
    text: "Mateo firmaba con el pulso alto. Luz dejaba sonar tres veces. Al año, uno tenía movimiento; la otra, suelo.",
    note: "El timbre no es el enemigo. El enemigo es firmar sin haber oído.",
    image: "/cursos-assets/la-pausa-que-decide/02-reaccion-pausa.jpg",
    alt: "Dos velocidades en la misma calle",
  },
  {
    etapa: "1",
    kicker: "Puente bíblico",
    title: "El pie que se apresura",
    text: "«El que se apresura con los pies peca.» Proverbios 19:2. Santiago: pronto para oír, tardo para hablar.",
    note: "Jehová no pide lentitud por temor. Pide que el pie no vaya más rápido que la mirada.",
    image: "/cursos-assets/la-pausa-que-decide/01-portada-pausa-decide.jpg",
    alt: "Pausa en el camino",
  },
  {
    etapa: "1",
    kicker: "Ejercicio",
    title: "Tres respiraciones antes del sí",
    text: "Una decisión que pida velocidad. Tres respiraciones. Una línea: qué habrías firmado sin la pausa.",
    note: "No corrijas el mundo. Recupera el volante una vez.",
    image: "/cursos-assets/la-pausa-que-decide/08-mente-filtro.jpg",
    alt: "Un espacio para pensar",
  },
  {
    etapa: "2",
    kicker: "Etapa 2 · Ver lo que no se ve",
    title: "La mente es un filtro, no una cámara",
    text: "Dos personas recorren el mismo lugar y no ven el mismo mapa. Lo evidente es la hoja. La causa suele ser raíz.",
    note: "Hay información de más y observación de menos.",
    image: "/cursos-assets/la-pausa-que-decide/03-bosque-dos-miradas.jpg",
    alt: "El mismo sendero, dos miradas",
  },
  {
    etapa: "2",
    kicker: "Etapa 2",
    title: "Admiramos la copa",
    text: "El árbol se sostiene donde nadie aplaude. Si podas la hoja y no tocas la raíz, vuelve la misma rama.",
    note: "Pregunta: qué no estoy viendo todavía.",
    image: "/cursos-assets/la-pausa-que-decide/04-raices-arbol.jpg",
    alt: "Raíces bajo la tierra",
  },
  {
    etapa: "2",
    kicker: "Etapa 2",
    title: "Las puertas no llegan con mariachi",
    text: "Los patrones se leen en lo que se repite. No adivinas el futuro: ves señales que aún no hacen ruido.",
    note: "A veces la oportunidad viene disfrazada de dificultad.",
    image: "/cursos-assets/la-pausa-que-decide/06-problema-maestro.jpg",
    alt: "Luz bajo la puerta",
  },
  {
    etapa: "2",
    kicker: "Cuento",
    title: "Dos en el mismo mezquite",
    text: "El sobrino miraba el huarache. El tío miró el polvo, el viento y el nido. El arroyo “que no había” ya estaba avisando.",
    note: "No era magia. Eran tres cosas más que el camino de enfrente.",
    image: "/cursos-assets/la-pausa-que-decide/03-bosque-dos-miradas.jpg",
    alt: "Mirar más que los pies",
  },
  {
    etapa: "2",
    kicker: "Puente bíblico",
    title: "Contar el costo",
    text: "Lucas 14:28: sentarse a calcular antes de la torre. Nehemías recorrió el muro de noche, antes de hablar.",
    note: "Jehová no pide que improvises la obra. Pide que mires el terreno.",
    image: "/cursos-assets/la-pausa-que-decide/09-planos-arquitecto.jpg",
    alt: "Planos sobre la mesa",
  },
  {
    etapa: "2",
    kicker: "Ejercicio",
    title: "Qué no estoy viendo",
    text: "Un roce. Tres renglones: lo evidente, una causa debajo, un detalle que ignoraste porque “no era el tema”.",
    note: "Sustituye “qué está pasando” por “qué no veo todavía”.",
    image: "/cursos-assets/la-pausa-que-decide/04-raices-arbol.jpg",
    alt: "Buscar la raíz",
  },
  {
    etapa: "3",
    kicker: "Etapa 3 · Decidir sin la tormenta",
    title: "No toda decisión merece la misma velocidad",
    text: "El miedo inventa amenazas. La euforia borra riesgos. La ira convierte un retraso en un juicio.",
    note: "En clima fuerte el cerebro reduce el mapa.",
    image: "/cursos-assets/la-pausa-que-decide/05-casa-tormenta.jpg",
    alt: "Construir bajo la lluvia",
  },
  {
    etapa: "3",
    kicker: "Etapa 3",
    title: "La emoción informa; no conduce",
    text: "Escuchar el clima es sabiduría. Entregarle la pluma es otra cosa. Rectificar a tiempo no es fracaso.",
    note: "La certeza absoluta no llega. Esperarla es postergar con traje elegante.",
    image: "/cursos-assets/la-pausa-que-decide/05-casa-tormenta.jpg",
    alt: "Esperar bajo el alero",
  },
  {
    etapa: "3",
    kicker: "Cuento",
    title: "El albañil y el chubasco",
    text: "“La losa no se arrepiente; tú sí.” Perdieron una tarde. Ganaron el techo. El vecino coló bajo el agua y rascó grietas un año.",
    note: "La prisa cobra con intereses.",
    image: "/cursos-assets/la-pausa-que-decide/05-casa-tormenta.jpg",
    alt: "La tormenta pasa; el cimiento no",
  },
  {
    etapa: "3",
    kicker: "Puente bíblico",
    title: "Ciudad sin muro",
    text: "Proverbios 25:28: sin rienda, la plaza se saquea. 16:9: el corazón piensa; Jehová afirma los pasos.",
    note: "El muro no es dureza contra el corazón. Es borde para que el clima no firme.",
    image: "/cursos-assets/la-pausa-que-decide/01-portada-pausa-decide.jpg",
    alt: "Elegir el paso",
  },
  {
    etapa: "3",
    kicker: "Ejercicio",
    title: "Consejo al que más quieres",
    text: "Escribe la decisión como si se la aconsejaras a quien más amas. ¿Le pedirías que duerma? Usa esa frase contigo.",
    note: "Marca: ¿esto se decide en minutos o en días?",
    image: "/cursos-assets/la-pausa-que-decide/09-planos-arquitecto.jpg",
    alt: "Pensar el camino",
  },
  {
    etapa: "4",
    kicker: "Etapa 4 · El problema como maestro",
    title: "Dos piezas en cada obstáculo",
    text: "El golpe que se ve y la habilidad que pide. Quien solo busca culpables pierde la segunda pieza.",
    note: "El fracaso, bien leído, es un camino que ya no tienes que repetir.",
    image: "/cursos-assets/la-pausa-que-decide/06-problema-maestro.jpg",
    alt: "Puerta y luz",
  },
  {
    etapa: "4",
    kicker: "Etapa 4",
    title: "No se decide en el minuto más alto",
    text: "El miedo estrecha el mapa. Primero el cuerpo. Luego los hechos. Al final, el paso.",
    note: "La calma no es adorno. Es ventaja.",
    image: "/cursos-assets/la-pausa-que-decide/08-mente-filtro.jpg",
    alt: "Bajar el ruido",
  },
  {
    etapa: "4",
    kicker: "Cuento",
    title: "El puesto que cerró",
    text: "El mismo golpe. Uno dijo “ya no hay sitio”. El otro hizo inventario del error y armó un taller más limpio.",
    note: "El maestro no era el mercado. Era lo que cada uno hizo con el error.",
    image: "/cursos-assets/la-pausa-que-decide/06-problema-maestro.jpg",
    alt: "Lo cerrado puede ser umbral",
  },
  {
    etapa: "4",
    kicker: "Puente bíblico",
    title: "José y el granero",
    text: "No eligió el pozo. Eligió guardar en los años gordos (Génesis 41). Leer el patrón antes de que el hambre haga ruido.",
    note: "Jehová no promete una vida sin sequía. Promete que se puede administrar con claridad.",
    image: "/cursos-assets/la-pausa-que-decide/09-planos-arquitecto.jpg",
    alt: "Preparar con tiempo",
  },
  {
    etapa: "4",
    kicker: "Ejercicio",
    title: "Dos columnas",
    text: "Columna A: el golpe (hechos). Columna B: una sola habilidad que te pide. Si no sale B, duerme y vuelve.",
    note: "No el rumbo grande si el pulso sigue alto.",
    image: "/cursos-assets/la-pausa-que-decide/04-raices-arbol.jpg",
    alt: "Inventario del problema",
  },
  {
    etapa: "5",
    kicker: "Etapa 5 · Influir sin empujar",
    title: "La confianza se deposita",
    text: "Se puede obedecer por miedo. Solo se colabora por confianza. El discurso no cobra lo que el hecho no depositó.",
    note: "Escuchar para comprender abre la puerta que el argumento cierra.",
    image: "/cursos-assets/la-pausa-que-decide/07-confianza-escucha.jpg",
    alt: "Dos sillas, una escucha",
  },
  {
    etapa: "5",
    kicker: "Etapa 5",
    title: "Palabra y hecho en el mismo renglón",
    text: "Cada promesa cumplida es un depósito. Persuadir a palos despierta defensa. Una pregunta deja que la idea nazca adentro.",
    note: "El carácter se trabaja antes que la técnica.",
    image: "/cursos-assets/la-pausa-que-decide/07-confianza-escucha.jpg",
    alt: "La mesa de la conversación",
  },
  {
    etapa: "5",
    kicker: "Cuento",
    title: "El maestro que no corregía primero",
    text: "«¿Qué querías que hiciera esta esquina?» El aprendiz oyó su error sin humillación. El taller tuvo menos gritos y más piezas buenas.",
    note: "La influencia no fue el dedo. Fue la pregunta.",
    image: "/cursos-assets/la-pausa-que-decide/07-confianza-escucha.jpg",
    alt: "Dignidad en la mesa",
  },
  {
    etapa: "5",
    kicker: "Puente bíblico",
    title: "Respuesta blanda",
    text: "Proverbios 15:1: el tono abre o cierra. 15:22: los pensamientos se afirman con consejeros.",
    note: "Jehová no pide que impongas. Pide que no decidas sordo.",
    image: "/cursos-assets/la-pausa-que-decide/03-bosque-dos-miradas.jpg",
    alt: "Atención verdadera",
  },
  {
    etapa: "5",
    kicker: "Ejercicio",
    title: "Parafrasear antes de responder",
    text: "«Lo que oigo es…» Luego una pregunta, no un veredicto. Si el clima no cambia, quizá la cuenta estaba vacía.",
    note: "Entonces el trabajo no es el argumento. Es el depósito.",
    image: "/cursos-assets/la-pausa-que-decide/07-confianza-escucha.jpg",
    alt: "Oír de verdad",
  },
  {
    etapa: "6",
    kicker: "Etapa 6 · Cuidar la mente",
    title: "La libertad empieza adentro",
    text: "Una idea repetida parece verdad. El miedo es un pasajero útil. No se le da el volante.",
    note: "Quien no gobierna su atención habita un pensamiento prestado.",
    image: "/cursos-assets/la-pausa-que-decide/08-mente-filtro.jpg",
    alt: "Elegir lo que entra",
  },
  {
    etapa: "6",
    kicker: "Etapa 6",
    title: "¿Esta idea es mía?",
    text: "El sesgo guarda lo que te da la razón. Revisar una creencia con evidencia nueva es madurez, no debilidad.",
    note: "Cuidar la dieta mental como se cuida el plato.",
    image: "/cursos-assets/la-pausa-que-decide/08-mente-filtro.jpg",
    alt: "Libro y silencio",
  },
  {
    etapa: "6",
    kicker: "Cuento",
    title: "El radio que no se apagaba",
    text: "Soñaba los sustos del noticiero. Un domingo lo apagó. No se volvió ingenua. Se volvió capaz de oír su criterio.",
    note: "El aparato no era el enemigo. El enemigo era no elegir el programa.",
    image: "/cursos-assets/la-pausa-que-decide/08-mente-filtro.jpg",
    alt: "El teléfono boca abajo",
  },
  {
    etapa: "6",
    kicker: "Puente bíblico",
    title: "El simple cree toda palabra",
    text: "Proverbios 14:15: el avisado mira sus pasos. Filipenses 4:8 es dieta. Guardar el corazón incluye la entrada.",
    note: "Jehová no pide cinismo. Pide examen.",
    image: "/cursos-assets/la-pausa-que-decide/04-raices-arbol.jpg",
    alt: "Mirar con profundidad",
  },
  {
    etapa: "6",
    kicker: "Ejercicio",
    title: "Quién lo dice y para qué",
    text: "Una afirmación que te alteró. ¿Quién? ¿Qué gana si la creo? ¿Qué evidencia hay fuera de la emoción?",
    note: "Media hora menos de ruido esta noche.",
    image: "/cursos-assets/la-pausa-que-decide/08-mente-filtro.jpg",
    alt: "Examinar la idea",
  },
  {
    etapa: "7",
    kicker: "Etapa 7 · Diseñar el mañana",
    title: "El futuro no llega de visita",
    text: "Se construye con el ladrillo de hoy. Preguntar quién quieres ser en diez años simplifica los sí de esta semana.",
    note: "Lo invisible un mes es enorme en cinco años.",
    image: "/cursos-assets/la-pausa-que-decide/09-planos-arquitecto.jpg",
    alt: "Planos y luz de mañana",
  },
  {
    etapa: "7",
    kicker: "Etapa 7",
    title: "Identidad antes que anuncio",
    text: "No «quiero un libro»: «quiero ser alguien que escribe». El resultado tarda. La identidad empieza hoy.",
    note: "Todo sí es un no a otra cosa. Concentrar no es trabajar más: es intención.",
    image: "/cursos-assets/la-pausa-que-decide/09-planos-arquitecto.jpg",
    alt: "El papel que ordena el montón",
  },
  {
    etapa: "7",
    kicker: "Cuento",
    title: "La casa sin plano",
    text: "Compraba lo que el puesto traía cada sábado. Tenía un montón caro. El maestro le puso cuatro muros en un papel.",
    note: "El papel no era lujo. Era misericordia contra el capricho.",
    image: "/cursos-assets/la-pausa-que-decide/09-planos-arquitecto.jpg",
    alt: "Diseñar antes de amontonar",
  },
  {
    etapa: "7",
    kicker: "Puente bíblico",
    title: "Jehová afirma los pasos",
    text: "Proverbios 16:9: tú diseñas; no usurpas la soberanía. El árbol que debió plantarse hace veinte años se planta hoy.",
    note: "El maná era de cada día: constancia, no acaparar el futuro de un golpe.",
    image: "/cursos-assets/la-pausa-que-decide/10-disciplina-silenciosa.jpg",
    alt: "Un paso de cada día",
  },
  {
    etapa: "7",
    kicker: "Ejercicio",
    title: "El siguiente ladrillo",
    text: "Diez minutos: la persona de dentro de diez años. Una decisión de hoy que te acerque un palmo. Mañana, otro ladrillo.",
    note: "Anótalo donde lo veas al despertar.",
    image: "/cursos-assets/la-pausa-que-decide/09-planos-arquitecto.jpg",
    alt: "Un ladrillo, no un anuncio",
  },
  {
    etapa: "8",
    kicker: "Etapa 8 · Vivir como estratega",
    title: "Ya tienes una estrategia",
    text: "La pregunta es si te acerca a la vida que quieres o si las circunstancias la están escribiendo por ti.",
    note: "Cada hábito es estrategia. También lo que decides ignorar.",
    image: "/cursos-assets/la-pausa-que-decide/10-disciplina-silenciosa.jpg",
    alt: "El camino sin público",
  },
  {
    etapa: "8",
    kicker: "Etapa 8",
    title: "Disciplina silenciosa",
    text: "El trofeo se fotografía. El camino de las cinco de la mañana, casi nunca. La acción inteligente enseña más que la espera perfecta.",
    note: "Pausa, raíz, no firmar en tormenta, leer el problema, depositar, examinar, ladrillo, repetir.",
    image: "/cursos-assets/la-pausa-que-decide/10-disciplina-silenciosa.jpg",
    alt: "Amanecer de oficio",
  },
  {
    etapa: "8",
    kicker: "Cuento",
    title: "El camino de las cinco",
    text: "El pueblo aplaudió el día de la carrera. Él sabía que se había ganado en los lunes sin testigo.",
    note: "No necesita galería para ser verdadero.",
    image: "/cursos-assets/la-pausa-que-decide/10-disciplina-silenciosa.jpg",
    alt: "Sendero vacío",
  },
  {
    etapa: "8",
    kicker: "Puente bíblico",
    title: "Fiel en lo muy poco",
    text: "Lucas 16:10. Jehová no mide el ruido del resultado. Mide el ladrillo de hoy.",
    note: "La estrategia del Reino no es espectáculo. Es constancia a la vista de quien sí ve lo oculto.",
    image: "/cursos-assets/la-pausa-que-decide/01-portada-pausa-decide.jpg",
    alt: "Un paso consciente",
  },
  {
    etapa: "8",
    kicker: "Ejercicio",
    title: "Estrategia de veinticuatro horas",
    text: "Mañana: dónde la pausa, qué raíz, a quién escuchar, el ladrillo. Al anochecer, marca qué sí ocurrió.",
    note: "El cuaderno es para la cognición, no para la galería.",
    image: "/cursos-assets/la-pausa-que-decide/09-planos-arquitecto.jpg",
    alt: "Cuatro líneas para mañana",
  },
  {
    etapa: "Cierre",
    kicker: "Pregunta que te acompaña",
    title: "Arquitecto, no espectador",
    text: "Si mañana fueras el arquitecto de tu día, ¿cuál sería el primer ladrillo?",
    note: "La prisa puede volver. La pausa ya tiene asiento. Al lado del profesional, nunca en su lugar.",
    image: "/cursos-assets/la-pausa-que-decide/01-portada-pausa-decide.jpg",
    alt: "El cruce, otra vez, con elección",
  },
]
